<?php

namespace BackEnd\DataBaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipacionesRepository extends EntityRepository
{
}
