<?php

namespace BackEnd\DataBaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * tipo_EventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipo_EventoRepository extends EntityRepository
{
}
