#definición de la seguridad.
fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

back_end_data_base:
    resource: "@BackEndDataBaseBundle/Resources/config/routing.yml"
    prefix:   /

dawplantilla:
    resource: "@DawplantillaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#Ruta para el registro.
fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /register

#Ruta para ver el profile.
fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /profile

#Ruta para cambiar el password.
fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /change_password

#Ruta para resetar el password.
fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting
