# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
  encoders:
    FOS\UserBundle\Model\UserInterface : sha512


  role_hierarchy:
    ROLE_ADMIN : ROLE_USER

  providers:
      fos_userbundle:
        id: fos_user.user_provider.username

  firewalls:
    main:
      pattern : ^/
      form_login:
        provider: fos_userbundle
        csrf_provider: security.csrf.token_manager
      logout: true
      anonymous: true
#Defiición de los permisos.
  access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY}
    - { path: ^/evento/new, role: ROLE_ADMIN}
