dawplantilla_homepage:
    path:     /prueba
    defaults: { _controller: DawplantillaBundle:Default:index }
    
prueba_homepage:    
    path:     /evento
    defaults: { _controller: DawplantillaBundle:Default:evento }
