dawplantilla_homepage:
    path:     /home
    defaults: { _controller: DawplantillaBundle:Default:index }
    
prueba_homepage:    
    path:     /mievento
    defaults: { _controller: DawplantillaBundle:Default:mievento }
    
categoria_hompage:
    path:   /categoria/{id}
    defaults: {_controller: DawplantillaBundle:Default:categoria}
    methods:  GET
