back_end_data_base_homepage:
    path:     /
    defaults: { _controller: BackEndDataBaseBundle:Default:index }

back_end_data_base_evento:
    resource: "@BackEndDataBaseBundle/Resources/config/routing/evento.yml"
    prefix:   /evento

back_end_data_base_participaciones:
    resource: "@BackEndDataBaseBundle/Resources/config/routing/participaciones.yml"
    prefix:   /participaciones
    
back_end_data_base_tipo_evento:
    resource: "@BackEndDataBaseBundle/Resources/config/routing/tipo_evento.yml"
    prefix:   /tipo_evento
